# Generated by Django 4.0.6 on 2022-07-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_unit',
            field=models.CharField(choices=[('s', 'Seconds'), ('m', 'Minutes'), ('h', 'Hours')], default='s', max_length=10),
        ),
    ]
