# Generated by Django 4.0.6 on 2022-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_photo_pair_id_alter_photo_pair_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_pair',
            name='ref_cred',
            field=models.CharField(default='dummy ref', max_length=250),
            preserve_default=False,
        ),
    ]
